package com.czxy.day03

/*
 * @Auther: 传智新星
 * @Date: 2020/1/30 09:11
 * @Description: 
    流年笑掷 未来可期。以梦为马,不负韶华!
 */
object _14ExceptionDemo {

  def main(args: Array[String]): Unit = {

    // 抛出一个异常
    // scala中抛出的异常不需要在方法体上声明
    throw new Exception("这是一个异常!")

  }
}
